### ISSUE TITLE
Error with 2 or more players with playlists

### ISSUE THREAD

**Issue by keymnsk** [manelpb/videojs-playlist-thumbs#3]
Hello.

If you create a number (2 ore more) of players with different playlists you can't properly change tracks. 
Only one playlist works, others are linked to it.

That's because of joint 'videos' object. 
Could you please divide scopes along different player instances.

**Comment by keymnsk** [comment]
I've made pull-request

**Comment by manelpb** [comment]
Thank you for the pull request. 

Merged
